### ISSUE TITLE
Code repository name

### ISSUE THREAD

**Issue by raortegar** [mebis-lp/moodle-mod_kanban#39]
Hi Team, 
Thanks for creating this super nice plugin! 
I've made a review on the code following the plugin contribution checklist documentation https://docs.moodle.org/dev/Plugin_contribution_checklist

And I have an small recommendation: 
According the Moodle documentation https://moodledev.io/general/community/plugincontribution/checklist#code-repository-name 
The repository name should use the standard frankenstyle Moodle naming convention which makes it easy for moodle admins to identify your plugin. The correct format to use is moodle-{plugintype}_{pluginname}.
So on this case it should be moodle-mod_kanban
Cheers.

**Comment by PhMemmel** [comment]
Fixed, thanks for the hint!
