### ISSUE TITLE
Discussion tiles shows html-code

### ISSUE THREAD

**Issue by ralfhilg** [mebis-lp/moodle-mod_kanban#41]
After creating a discussion topic the text shows html-code. 
![02-02-2024_12-25-31](https://github.com/mebis-lp/moodle-mod_kanban/assets/41056305/adda376d-3ea1-4301-9f32-3d898afd9233)

**Comment by PhMemmel** [comment]
Hi @ralfhilg,

thank you for opening the issue. This has been fixed since the original release which we linked for the plugin registration process. Please update to the release from a few hours ago and test again.

**Comment by ralfhilg** [comment]
Thanks I will try
