### ISSUE TITLE
Group boards don't work inside courses that enable "force group mode"

### ISSUE THREAD

**Issue by leshlush** [mebis-lp/moodle-mod_kanban#52]
If a course has "separate groups" or "visible groups" and enables "force group mode" to enforce those group rules on all course activities, then group boards will not be visible or accessible. Course managers must disable "force group mode" and manually apply "separate groups" or "visible groups" to each kanban at the activity level.

Tested in Moodle 4.3.

**Comment by sh-csg** [comment]
Thanks for reporting this! Will be fixed by #53
